#!/bin/sh
#-------------------------------------------------------------------------------
# reviewboard: mysql.sh
#
# Provision MySQL.
#-------------------------------------------------------------------------------
# The MIT License (MIT)
# Copyright (c) 2016 Brian Minard
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#-------------------------------------------------------------------------------
function usage {
	echo "Usage: ${0} --dbname <database name> --dbuser=<database user> --rootpw <password> --rbpw <password>"
	exit 1
}


DATABASE_NAME=""
DATABASE_USER=""
MYSQL_PASSWORD=""
REVIEW_BOARD_PASSWORD=""
while [[ $# -ge 2 ]]; do
	key="$1"
	case $key in
		--dbname)
			DATABASE_NAME="$2"
			shift
			;;
		--dbuser)
			DATABASE_USER="$2"
			shift
			;;
		--rbpw)
			REVIEW_BOARD_PASSWORD="$2"
			shift
			;;
		--rootpw)
			MYSQL_PASSWORD="$2"
			shift
			;;
		*)
			usage
			;;
	esac
	shift
done


[ -f ${MYSQL_PASSWORD} ] \
	&& [ -n "${DATABASE_NAME}" ] \
	&& [ -n "${DATABASE_USER}" ] \
	&& [ -f ${REVIEW_BOARD_PASSWORD} ] \
	|| usage


function password {
	readonly PLAINTEXT=`cat ${1}`; shift
	readonly ENCRYPTED="*"`echo "from hashlib import sha1; print sha1(sha1('${PLAINTEXT}').digest()).hexdigest()" | python - | tr "[:lower:]" "[:upper:]"`
	if [ -z "${ENCRYPTED}" ]; then
		exit 1
	fi
	echo ${ENCRYPTED}
}


readonly ENCRYPTED_MYSQL_PASSWORD=`password ${MYSQL_PASSWORD}`
readonly ENCRYPTED_REVIEW_BOARD_PASSWORD=`password ${REVIEW_BOARD_PASSWORD}`


cat<<_EOF
#!/bin/sh


# Generated by ${0} (commit `git log -n 1 --pretty="%h" ${0}`) on `date`. Do NOT edit.


function command {
	local command=\${1}; shift
	local service=\${1}; shift
	/usr/bin/systemctl \${command} \${service} \\
		&& /usr/bin/systemctl status \${service} | egrep -q "Active: active"
	if [ \$? -ne 0 ]; then
		exit 1
	fi
}


function start {
	command start \${1}
}


yum --assumeyes install http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm
yum --assumeyes update
yum --assumeyes install mysql-community-server
yum --assumeyes install mysql-community-devel.x86_64


cat<<__EOF >> /etc/my.cnf
[client]
default-character-set=utf8
[mysqld]
character-set-server=utf8
explicit_defaults_for_timestamp=1
__EOF


start mysqld
yum --assumeyes install expect
/usr/bin/expect<<__EOF
spawn "mysql_secure_installation"
expect "Enter current password for root (enter for none):" { send "\r" }
expect "Set root password?" { send "n\r" }
expect "Remove anonymous users?" { send "Y\r" }
expect "Disallow root login remotely?" { send "Y\r" }
expect "Remove test database and access to it?" { send "Y\r" }
expect "Reload privilege tables now?" { send "Y\r" }
expect eof
__EOF

mysql -u root<<__EOF
create database ${DATABASE_NAME} character set utf8;
create user '${DATABASE_USER}'@'localhost' identified by password '${ENCRYPTED_REVIEW_BOARD_PASSWORD}';
grant all privileges on ${DATABASE_NAME}.* to '${DATABASE_USER}'@'localhost';
update mysql.user set password='${ENCRYPTED_MYSQL_PASSWORD}' where User='root';
__EOF
/usr/bin/systemctl stop mysqld


start mysqld
_EOF
