#!/bin/sh
#-------------------------------------------------------------------------------
# Provision the Review Board site.
#-------------------------------------------------------------------------------
# The MIT License (MIT)
# Copyright (c) 2016 Brian Minard
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#-------------------------------------------------------------------------------
function usage {
	echo "Usage: ${0} --dbname <database name> --dbuser=<database user> --rbpw <password> --admin <password>"
	exit 1
}


ADMIN_PASSWORD=""
DATABASE_NAME=""
DATABASE_USER=""
DATABASE_PASSWORD=""
while [[ $# -ge 2 ]]; do
	key="$1"
	case $key in
		--admin)
			ADMIN_PASSWORD="$2"
			shift
			;;
		--dbname)
			DATABASE_NAME="$2"
			shift
			;;
		--dbuser)
			DATABASE_USER="$2"
			shift
			;;
		--rbpw)
			DATABASE_PASSWORD="$2"
			shift
			;;
		*)
			usage
			;;
	esac
	shift
done


[ -n "${ADMIN_PASSWORD}" ] \
	&& [ -n "${DATABASE_NAME}" ] \
	&& [ -n "${DATABASE_USER}" ] \
	&& [ -f ${DATABASE_PASSWORD} ] \
	|| usage


readonly SITE_DIR=/var/www/reviews
readonly DOMAIN_NAME=reviewboard.local # Also defined in Vagrantfile.


cat<<_EOF
#!/bin/sh


# Generated by ${0} (commit `git log -n 1 --pretty="%h" ${0}`) on `date`. Do NOT edit.


rb-site install ${SITE_DIR} \
		--admin-email=admin@${DOMAIN_NAME} \
		--admin-pass=`cat ${ADMIN_PASSWORD}` \
		--admin-user=admin \
		--cache-type=memcached \
		--db-host=localhost \
		--db-name=${DATABASE_NAME} \
		--db-pass=`cat ${DATABASE_PASSWORD}` \
		--db-type=mysql \
		--db-user=${DATABASE_USER} \
		--domain-name=http://${DOMAIN_NAME} \
		--noinput \
		--python-loader=wsgi \
		--web-server-port=80 \
		--web-server-type=apache \
	&& chown -R apache ${SITE_DIR}/htdocs/media/uploaded ${SITE_DIR}/data
_EOF
